url: "https://juljankrause.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Juljan Krause" # the name of your site, e.g. ACME Corp.
description: "⟨quantum, cloud, AI | infrastructure & control⟩"
remote_theme: LeNPaul/academic

plugins:
  - jekyll-remote-theme
