# url: "https://juljankrause.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://juljankrause.com
baseurl:
title: "Juljan Krause" # the name of your site, e.g. ACME Corp.
description: "⟨quantum, cloud, AI | infrastructure & control⟩"
author: Juljan Krause
keywords: Juljan Krause, Georgia Tech, quantum internet, cybersecurity, international security, technology policy, quantum computing, quantum communication, technology governance, strategic competition
lang: en
serve_og_meta: true
serve_schema_org: true
remote_theme: LeNPaul/academic

plugins:
  - jekyll-remote-theme
